//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCRIBE.StreamDeck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCRIBE.StreamDeck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Common.
        /// </summary>
        internal static string ImagesCommon {
            get {
                return ResourceManager.GetString("ImagesCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Conversion.
        /// </summary>
        internal static string ImagesConversion {
            get {
                return ResourceManager.GetString("ImagesConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Date.
        /// </summary>
        internal static string ImagesDate {
            get {
                return ResourceManager.GetString("ImagesDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Common\Default.
        /// </summary>
        internal static string ImagesDefault {
            get {
                return ResourceManager.GetString("ImagesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Common\Files.
        /// </summary>
        internal static string ImagesFiles {
            get {
                return ResourceManager.GetString("ImagesFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Common\Folders.
        /// </summary>
        internal static string ImagesFolders {
            get {
                return ResourceManager.GetString("ImagesFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Logical.
        /// </summary>
        internal static string ImagesLogical {
            get {
                return ResourceManager.GetString("ImagesLogical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Lookup.
        /// </summary>
        internal static string ImagesLookup {
            get {
                return ResourceManager.GetString("ImagesLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Math.
        /// </summary>
        internal static string ImagesMath {
            get {
                return ResourceManager.GetString("ImagesMath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Miscellaneous.
        /// </summary>
        internal static string ImagesMiscellaneous {
            get {
                return ResourceManager.GetString("ImagesMiscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Text.
        /// </summary>
        internal static string ImagesText {
            get {
                return ResourceManager.GetString("ImagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\UserDefined.
        /// </summary>
        internal static string ImagesUserDefined {
            get {
                return ResourceManager.GetString("ImagesUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images\Common\Web.
        /// </summary>
        internal static string ImagesWeb {
            get {
                return ResourceManager.GetString("ImagesWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SCRIBE {
            get {
                object obj = ResourceManager.GetObject("SCRIBE", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Elgato\StreamDeck.
        /// </summary>
        internal static string StreamDeckInstallLocation {
            get {
                return ResourceManager.GetString("StreamDeckInstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\SCRIBE.Functions.xml.
        /// </summary>
        internal static string XMLFile {
            get {
                return ResourceManager.GetString("XMLFile", resourceCulture);
            }
        }
    }
}
